### ISSUE TITLE
Error when running `httproxy` command (0.9.0)

### ISSUE THREAD

**Issue by vladiibine** [ambv/httproxy#5]
```
$ httproxy 
Traceback (most recent call last):
  File "/home/vlad.ardelean/ve/tmp2/bin/httproxy", line 25, in <module>
    main()
  File "/home/vlad.ardelean/ve/tmp2/local/lib/python2.7/site-packages/httproxy.py", line 423, in main
    read_from, args = handle_configuration()
  File "/home/vlad.ardelean/ve/tmp2/local/lib/python2.7/site-packages/httproxy.py", line 390, in handle_configuration
    inifile['DEFAULT'] = default_args
AttributeError: ConfigParser instance has no attribute '__setitem__'
```

These are the dependencies that got installed:

```
Downloading/unpacking configparser (from httproxy)
  Downloading configparser-3.3.0r2.tar.gz
  Running setup.py (path:/home/3pillar.corp/vlad.ardelean/ve/tmp2/build/configparser/setup.py) egg_info for package configparser

Downloading/unpacking docopt (from httproxy)
  Downloading docopt-0.6.2.tar.gz
  Running setup.py (path:/home/3pillar.corp/vlad.ardelean/ve/tmp2/build/docopt/setup.py) egg_info for package docopt

Installing collected packages: httproxy, configparser, docopt
  Running setup.py install for httproxy

    changing mode of build/scripts-2.7/httproxy from 644 to 755
    changing mode of /home/3pillar.corp/vlad.ardelean/ve/tmp2/bin/httproxy to 755
  Running setup.py install for configparser
    deleting configparser.egg-info/requires.txt
```

**Comment by bingtel** [comment]
httproxy -H 0.0.0.0 -p 10000
Traceback (most recent call last):
  File "/home/fee/httproxy/venv/bin/httproxy", line 25, in <module>
    main()
  File "/home/fee/httproxy/venv/local/lib/python2.7/site-packages/httproxy.py", line 423, in main
    read_from, args = handle_configuration()
  File "/home/fee/httproxy/venv/local/lib/python2.7/site-packages/httproxy.py", line 397, in handle_configuration
    iniconf = dict(inifile['main'])
  File "/home/fee/httproxy/venv/local/lib/python2.7/site-packages/backports/configparser/__init__.py", line 979, in __getitem__
    raise KeyError(key)
KeyError: 'main'
